name: haskell-algo
version: 0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- array
- containers
- deepseq
- mtl

ghc-options: -Wall -fno-warn-name-shadowing

library:
  source-dirs: src

tests:
  test-all:
    source-dirs: tests
    main: Spec.hs
    ghc-options: -fno-warn-orphans
    dependencies:
    - haskell-algo
    - hspec
    - QuickCheck

benchmarks:
  bench-all:
    source-dirs: bench
    main: Bench.hs
    ghc-options: -O2
    dependencies:
    - haskell-algo
    - criterion
    - MonadRandom
    - random
    - random-shuffle

executables:
  gen-summary:
    source-dirs: bench-out
    main: GenSummary.hs
    dependencies:
    - containers
    - csv
    - table-layout
    - text
