name: haskell-algo
version: 0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- array

ghc-options: -Wall -fno-warn-name-shadowing

library:
  source-dirs: src

tests:
  all:
    source-dirs: tests
    main: Spec.hs
    ghc-options: -fno-warn-orphans
    dependencies:
    - haskell-algo
    - hspec
    - QuickCheck
