name: haccepted
version: 0.1.0.0
synopsis: Data structures and algorithms
description: Data structures and algorithms for competitive programming in Haskell

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- containers
- deepseq
- mtl

ghc-options: -Wall -fno-warn-name-shadowing

library:
  source-dirs: src

tests:
  test-all:
    source-dirs: tests
    main: Spec.hs
    ghc-options: -fno-warn-orphans
    dependencies:
    - haccepted
    - hspec
    - QuickCheck

benchmarks:
  bench-all:
    source-dirs: bench
    main: Bench.hs
    ghc-options: -O2 -fno-warn-orphans
    dependencies:
    - haccepted
    - criterion
    - MonadRandom
    - random

executables:
  gen-summary:
    source-dirs: bench-out
    main: GenSummary.hs
    dependencies:
    - containers
    - csv
    - table-layout
    - text

  rewrite-srcs:
    source-dirs: gendocs
    main: RewriteSrcs.hs
    dependencies:
    - filepath
